//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoldingDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstance
    {
        public int ConnectionId { get; set; }
        public int UserId { get; set; }
        public string InstanceId { get; set; }
        public string InstanceName { get; set; }
        public string PublicToken { get; set; }
        public string AccessToken { get; set; }
    }
}
